name : CI-Perf
on: 
  push: 
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: JMeter Test
      uses: QAInsights/PerfAction@3.0
      with:
        test-plan-path: My_test.jmx
        args: ""
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: result.jtl

