name : CI-Perf
on: 
  push: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: JMeter Test
      uses: QAInsights/PerfAction@3.0
      with:
        test-plan-path: 'My_test.jmx'
        args: ""
