name : CI-Perf
on: 
  push: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: JMeter Test
      uses: QAInsights/PerfAction@3.0
      with:
        test-plan-path: './My_test.jmx'
        args: ""
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: result.jtl

