name : CI-Perf
on: 
push:
  branches: [main]
pull_request:
  branches:[main]
  
workflow-dispatch:

jobs:

build:
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v2
- name: PerfAction for JMeter
  # You may pin to the exact commit or the version.
  # uses: QAInsights/PerfAction@e9460cd32edbd6686068034e4b2d5c0fa7a1568d
  uses: QAInsights/PerfAction@3.0
  with:
    # jmeter test plan to execute
    test-plan-path: ./Case-study-user.jmx
    # Optional arguments. For more details https://jmeter.apache.org/usermanual/get-started.html#non_gui
    args: # optional
    
- name: Upload Results
  uses: actions/upload-artifact@v2
  with:
    name: jmeter-results
    path: result.jtl
